module.exports = {
    additional: null,
    article: null,
    brand: null,
    catalog_id: null,
    catalogs: null,
    currency: null,
    description: null,
    external_id: null,
    image: null,
    model: null,
    name: null,
    price: null,
    rating: null,
    region: null,
    resource_id: null,
    reviews: null,
    uniform_name: null,
    url: null
}