module.exports = {
    additional: nil,
    article: nil,
    brand: nil,
    catalog_id: nil,
    catalogs: nil,
    currency: nil,
    description: nil,
    external_id: nil,
    image: nil,
    model: nil,
    name: nil,
    price: nil,
    rating: nil,
    region: nil,
    resource_id: nil,
    reviews: nil,
    uniform_name: nil,
    url: nil
}